### PR TITLE
CAF-2192: Updated Document Worker Error Handling.

### PR DESCRIPTION
**Pull request by aaronoloughlin**
Updated Document Worker Error Handling to mention 'addFailures()'.

### CODE REVIEW

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
In truth that is not a great example, since `KVERR_FormatNotSupported` should be or make up part of the failure id, and the failure message should describe it.

**Comment by aaronoloughlin** [comment]
Updated the 'addFailure' example.
Ready again for review.

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
Undo your spelling change - all documentation should be in US English.

**Comment by aaronoloughlin** [comment]
Updated to US English.
Ready for review.

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
